project_id = "fqcwnosotuzbfoyioqzw"

[functions.sarkar-api]
verify_jwt = false

[functions.check-ip]
verify_jwt = false

[functions.ghost-admin]
verify_jwt = false

[functions.ip-manager]
verify_jwt = false

[functions.shieldwall-check]
verify_jwt = false

[functions.login-lockout]
verify_jwt = false

[functions.telegram-otp]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false
